"""Initial migration

Revision ID: 2cd14cb836d1
Revises: 0c8d0632f9bf
Create Date: 2024-10-21 17:40:13.476886

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cd14cb836d1'
down_revision: Union[str, None] = '0c8d0632f9bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_feedback', sa.Column('feedback_text', sa.String(), nullable=True))
    op.drop_column('user_game_feedback', 'feedback')
    op.add_column('user_game_ratings', sa.Column('rating_int', sa.Integer(), nullable=True))
    op.drop_column('user_game_ratings', 'rating')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_game_ratings', sa.Column('rating', sa.INTEGER(), nullable=True))
    op.drop_column('user_game_ratings', 'rating_int')
    op.add_column('user_game_feedback', sa.Column('feedback', sa.VARCHAR(), nullable=True))
    op.drop_column('user_game_feedback', 'feedback_text')
    # ### end Alembic commands ###
